### ISSUE TITLE
php error?

### ISSUE THREAD

**Issue by 2600box** [zenbuffy/LiteraryClock#6]
I get these php errors when trying to generate images. Any ideas?

Thanks!

```
#lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

`apt install php7.4-cli php-gd php-imagick imagemagick`

```
# php -v
PHP 7.4.3-4ubuntu2.17 (cli) (built: Jan 10 2023 15:37:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3-4ubuntu2.17, Copyright (c), by Zend Technologies
```

```
Notice: Trying to access array offset on value of type bool in /root/LiteraryClock/quote_to_image.php on line 287
PHP Notice:  Trying to access array offset on value of type bool in /root/LiteraryClock/quote_to_image.php on line 287
```

**Comment by zenbuffy** [comment]
I'm wondering if it's a ttf vs otf font issue and the method in question can't locate the fonts on your system? There's a new commit that has the files in otf also, you could try commenting out the ttf and using the otf definitions and maybe that'll work.

**Comment by zenbuffy** [comment]
I received the same error while trying to run for the first time on a machine without Imagemagick installed. Is that installed and in the path where you are trying to run?

**Comment by 2600box** [comment]
I think it was a php memory issue, though I have forgotten now. Thanks though!
